In [1]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y, x.shape

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]), torch.Size([1]))

In [2]:
x = torch.arange(4)
x, x.shape

(tensor([0, 1, 2, 3]), torch.Size([4]))

In [3]:
x[3]

tensor(3)

In [4]:
len(x)

4

In [5]:
z = torch.tensor(3)
z.shape, x.shape

(torch.Size([]), torch.Size([4]))

In [6]:
A = torch.arange(20).reshape(4, 5)
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [7]:
# 横向对比
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [10]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [11]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

我详细写重写出每一段代码的目的是加深印象，因为我在边打边学

In [12]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A, A + B, A == B, A * B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

In [13]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [14]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [15]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [16]:
A = torch.arange(40, dtype=torch.float32).reshape(2, 5, 4)
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

In [17]:
A_sum_axis0 = A.sum(axis=0, keepdims=True)
#第零维求和，即此三维数组的深度求和
A, A_sum_axis0, A_sum_axis0.shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]]]),
 torch.Size([1, 5, 4]))

In [18]:
A_sum_axis1 = A.sum(axis=1, keepdims=True)
#行求和
A, A_sum_axis1, A_sum_axis1.shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[[ 40.,  45.,  50.,  55.]],
 
         [[140., 145., 150., 155.]]]),
 torch.Size([2, 1, 4]))

In [19]:
A_sum_axis2 = A.sum(axis=2, keepdims=True)
#列求和
A, A_sum_axis2, A_sum_axis2.shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[[  6.],
          [ 22.],
          [ 38.],
          [ 54.],
          [ 70.]],
 
         [[ 86.],
          [102.],
          [118.],
          [134.],
          [150.]]]),
 torch.Size([2, 5, 1]))

In [20]:
A_sum_axis0_1 = A.sum(axis=[0, 1])
A, A.shape, A_sum_axis0_1, A_sum_axis0_1.shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 torch.Size([2, 5, 4]),
 tensor([180., 190., 200., 210.]),
 torch.Size([4]))

In [21]:
A_sum_axis0_1_2 = A.sum([0, 1, 2])
A, A.shape, A_sum_axis0_1_2, A_sum_axis0_1_2.shape, A.sum(), A.sum().shape
#标量的没有具体的size,所以[]内部没有具体的表示

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 torch.Size([2, 5, 4]),
 tensor(780.),
 torch.Size([]),
 tensor(780.),
 torch.Size([]))

In [22]:
A.mean(), A.sum() / A.numel()
A.mean() ==  A.sum() / A.numel()

#注意在此处有过报错，因为我没有将A定义为float32,而最开始的long是无法进行mean()运算的

tensor(True)

In [23]:
A, A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

如果我们不想舍去求和的维度，那么可以借助一下广播机制

In [24]:
sum_A = A.sum(axis=2, keepdims=True)
sum_A

tensor([[[  6.],
         [ 22.],
         [ 38.],
         [ 54.],
         [ 70.]],

        [[ 86.],
         [102.],
         [118.],
         [134.],
         [150.]]])

In [25]:
#我们来看看没有keepdims=True会怎么样
sum_A = A.sum(axis=2)
sum_A,sum_A.shape

(tensor([[  6.,  22.,  38.,  54.,  70.],
         [ 86., 102., 118., 134., 150.]]),
 torch.Size([2, 5]))

我们发现自然而然的就少了一个维度了，那么我们这样是无法进行广播操作的

In [26]:
sum_A = A.sum(axis=2, keepdims=True)
sum_A

tensor([[[  6.],
         [ 22.],
         [ 38.],
         [ 54.],
         [ 70.]],

        [[ 86.],
         [102.],
         [118.],
         [134.],
         [150.]]])

In [27]:
A / sum_A, A

(tensor([[[0.0000, 0.1667, 0.3333, 0.5000],
          [0.1818, 0.2273, 0.2727, 0.3182],
          [0.2105, 0.2368, 0.2632, 0.2895],
          [0.2222, 0.2407, 0.2593, 0.2778],
          [0.2286, 0.2429, 0.2571, 0.2714]],
 
         [[0.2326, 0.2442, 0.2558, 0.2674],
          [0.2353, 0.2451, 0.2549, 0.2647],
          [0.2373, 0.2458, 0.2542, 0.2627],
          [0.2388, 0.2463, 0.2537, 0.2612],
          [0.2400, 0.2467, 0.2533, 0.2600]]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]))

In [28]:
A.cumsum(axis=0), A
#第零维的累加求和

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]))

In [29]:
A.cumsum(axis=1), A

(tensor([[[  0.,   1.,   2.,   3.],
          [  4.,   6.,   8.,  10.],
          [ 12.,  15.,  18.,  21.],
          [ 24.,  28.,  32.,  36.],
          [ 40.,  45.,  50.,  55.]],
 
         [[ 20.,  21.,  22.,  23.],
          [ 44.,  46.,  48.,  50.],
          [ 72.,  75.,  78.,  81.],
          [104., 108., 112., 116.],
          [140., 145., 150., 155.]]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]))

In [30]:
A.cumsum(axis=2), A

(tensor([[[  0.,   1.,   3.,   6.],
          [  4.,   9.,  15.,  22.],
          [  8.,  17.,  27.,  38.],
          [ 12.,  25.,  39.,  54.],
          [ 16.,  33.,  51.,  70.]],
 
         [[ 20.,  41.,  63.,  86.],
          [ 24.,  49.,  75., 102.],
          [ 28.,  57.,  87., 118.],
          [ 32.,  65.,  99., 134.],
          [ 36.,  73., 111., 150.]]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]))

In [31]:
a = torch.ones(4, dtype=torch.float32)
b = torch.arange(4, dtype=torch.float32)
#意思是全部定义为为1的向量
a, b, torch.dot(a, b)
#pytorch的dot()运算只适用于一维向量

(tensor([1., 1., 1., 1.]), tensor([0., 1., 2., 3.]), tensor(6.))

In [32]:
torch.dot(a, b) == torch.sum(a * b), torch.dot(a, b).shape

(tensor(True), torch.Size([]))

In [33]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A, b, A.shape, b.shape, torch.mv(A, b)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [34]:
B = torch.ones(12, dtype=torch.float32).reshape(4, 3)
C = torch.ones(4, 3)
A, B, torch.mm(A, B), C == B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True],
         [True, True, True]]))

In [35]:
#范数操作,注意需要int和float，而long型是不参与norm()运算的
u = torch.tensor([2.0, 2.0, 2.0, 2.0])
v = torch.arange(12*2, dtype=torch.float32).reshape(2, 4, 3)
torch.norm(u), v

(tensor(4.),
 tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.],
          [ 6.,  7.,  8.],
          [ 9., 10., 11.]],
 
         [[12., 13., 14.],
          [15., 16., 17.],
          [18., 19., 20.],
          [21., 22., 23.]]]))

In [36]:
torch.abs(u).sum(), torch.abs(v).sum()

(tensor(8.), tensor(276.))

以上求的是$L_1$范数,下面是佛罗贝尼乌斯范数$L_F$

In [37]:
torch.norm(torch.ones(4, 9)), torch.ones(4, 9)

(tensor(6.),
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]))